run day year="2023":
  nvim --clean ../puzzles/{{year}}/{{day}}/input -s {{year}}/{{day}}/solution

encode:
  #!/usr/bin/env bash
  for year in ./*; do
    if [ -d $year ]; then
      for day in $year/*; do
        base64 "$day/solution" > "$day/encoded_solution"
      done
    fi
  done

decode:
  #!/usr/bin/env bash
  for year in ./*; do
    if [ -d $year ]; then
      for day in $year/*; do
        base64 "$day/encoded_solution" > "$day/solution"
      done
    fi
  done
