default:
  just --choose

run day part:
  (cd ../../common/rust/aoc; cargo run --release -- run {{day}} {{part}} 2023)

drun day part:
  (cd ../../common/rust/aoc; cargo run -- run {{day}} {{part}} 2023)

mrun day part:
  (cd ../../common/rust/aoc; cargo run --release -- --minimal run {{day}} {{part}} 2023)

test day part:
  (cd ../../common/rust/aoc; cargo run -- test {{day}} {{part}} 2023)

watch:
  watchexec -c clear -w src cargo test

bench day:
  cargo bench --bench day_{{day}}

submit day part:
  #!/usr/bin/env bash
  cd ../../common/rust/aoc
  answer=$(cargo run --release -- --minimal run {{day}} {{part}} 2023)
  echo "Submitting answer for day {{day}} part {{part}}: $answer"
  aoc submit --day {{day}} --year 2023 {{part}} "$answer"

puzzle day:
  (cd ../..; just puzzle {{day}} 2023)

