default:
  just --choose

watch year="2023" op="test":
  watchexec -c clear -w aoc_{{year}}/src just {{op}}

run day part year="2023":
  cargo run -- run {{day}} {{part}} {{year}}

sample day part year="2023":
  cargo run -- test {{day}} {{part}} {{year}}

test year="2023":
  (cd ./aoc_{{year}} ; cargo test)

bench day year="2023":
  (cd ./aoc_{{year}} ; cargo bench --bench day_{{day}})
